version: '3.8'
services:
  php:
    container_name: roller_coaster_php
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
       - ./app/php:/app
    env_file:
       - ./app/app.env
  
  nginx:
    container_name: roller_coaster_nginx
    build: ./nginx/
    depends_on:
      - php
    ports:
      - 8088:80



