version: '3.8'
services:
  php:
    container_name: roller_coaster_php
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
       - ./app/php:/app
    ports:
      - 9999:9000
    env_file:
       - ./app/app.env
  
  nginx:
    container_name: roller_coaster_nginx
    build: ./nginx/
    ports:
      - 8088:80
    volumes:
      - ./app/php/:/app



